#!/usr/bin/env python3
"""Render a private, portable snapshot. Contains no broker credentials or write actions."""
import argparse, html, json
from pathlib import Path
from journal import Journal

def render(state):
    esc=lambda x:html.escape(str(x))
    snapshot=state.get('snapshot') or {}; portfolio=snapshot.get('portfolio') or {}
    def money(x):
        try: return '${:,.2f}'.format(float(x))
        except (TypeError,ValueError): return 'Unavailable'
    def table(rows,fields):
        if not rows: return '<p class="empty">No records in this snapshot.</p>'
        return '<div class="overflow"><table><thead><tr>'+''.join('<th>'+esc(k.replace('_',' ').title())+'</th>' for k in fields)+'</tr></thead><tbody>'+''.join('<tr>'+''.join('<td>'+esc(r.get(k,'—'))+'</td>' for k in fields)+'</tr>' for r in rows)+'</tbody></table></div>'
    positions=snapshot.get('positions') or []; orders=snapshot.get('orders') or []
    stats=[('Account value',money(portfolio.get('total_value'))),('Cash',money(portfolio.get('cash'))),('Buying power',money((portfolio.get('buying_power') or {}).get('buying_power'))),('Workflow',state['mode'].title())]
    cards=''.join('<article class="stat"><span>'+esc(k)+'</span><strong>'+esc(v)+'</strong></article>' for k,v in stats)
    bots=''.join('<article class="bot"><span class="tag">RESEARCH PROFILE</span><h3>'+esc(b['name'])+'</h3><p>'+esc(b['strategy'])+'</p><small>'+esc(', '.join(b.get('symbols',[])))+'</small></article>' for b in state['bots']) or '<p>No strategy profiles yet. Ask Sentinel to create one.</p>'
    proposals=''.join('<details><summary>'+esc(p['intent']['symbol'])+' · '+esc(p['intent']['side'])+' · '+esc(p['status'])+'</summary><pre>'+esc(json.dumps(p,indent=2,ensure_ascii=False))+'</pre></details>' for p in state['proposals']) or '<p class="empty">No trade proposals. Research first, then review exact terms with Sentinel.</p>'
    errors=''.join('<p class="notice">'+esc(x)+'</p>' for x in snapshot.get('errors',[]))
    research=state.get('research',[])
    if research:
        latest=research[-1]
        proposals='<h3>'+esc(latest['title'])+'</h3><p>'+esc(latest.get('conclusion',''))+'</p>'+''.join('<details><summary>'+esc(p.get('role','Perspective'))+'</summary><p>'+esc(p.get('analysis',''))+'</p></details>' for p in latest['committee'])+'<p><small>One model, four analytical perspectives. '+esc(latest['createdAt'])+'</small></p>'+proposals
    return '''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta http-equiv="Content-Security-Policy" content="default-src 'none'; style-src 'unsafe-inline'"><title>Sentinel · Private trading companion</title><style>
    :root{color-scheme:dark;font-family:system-ui,-apple-system,sans-serif;background:#0a1017;color:#e8edf2}*{box-sizing:border-box}body{margin:0}header{border-bottom:1px solid #24303d;padding:24px 5vw;display:flex;justify-content:space-between;align-items:center}.brand{font-size:22px;font-weight:750;letter-spacing:-.7px}.brand b{color:#65dfbb;margin-right:12px}.tag{font-size:10px;letter-spacing:1.5px;color:#8ea1b6}main{max-width:1180px;padding:48px 24px;margin:auto}h1{font-size:clamp(32px,5vw,50px);letter-spacing:-2px;margin:8px 0}h2{font-size:20px}p,small{color:#a2b0bf;line-height:1.65}.intro{max-width:650px}.status{display:inline-block;color:#ffd28c;border:1px solid #664e2d;background:#2e261b;padding:7px 12px;border-radius:30px;font-size:12px}.stats{display:grid;grid-template-columns:repeat(4,1fr);gap:14px;margin:32px 0}.stat,.panel,.bot{background:#111b26;border:1px solid #243342;border-radius:16px;padding:24px}.stat span{color:#93a4b6;font-size:13px}.stat strong{display:block;font-size:29px;margin-top:14px;font-weight:550}.panel{margin:18px 0}.row{display:flex;justify-content:space-between;gap:18px;align-items:center}.bots{display:grid;grid-template-columns:repeat(2,1fr);gap:14px}.bot{background:#13232c}table{width:100%;border-collapse:collapse;text-align:left;font-size:14px}th,td{padding:14px 10px;border-bottom:1px solid #283646}th{font-weight:500;color:#899fb4}code{background:#1d2c3a;padding:4px 6px;border-radius:4px}pre{white-space:pre-wrap;overflow-wrap:anywhere;color:#b8c6d3;font-size:12px}.empty{padding:12px 0}.overflow{overflow:auto}.notice{padding:16px;border-left:3px solid #d6ae6a;background:#201f1b}summary{cursor:pointer;padding:16px 0}footer{margin-top:30px;color:#7c8e9e;font-size:12px}@media(max-width:700px){.stats{grid-template-columns:repeat(2,1fr)}.bots{grid-template-columns:1fr}.row{align-items:flex-start;flex-direction:column}main{padding:28px 16px}.stat{padding:16px}.stat strong{font-size:24px}}
    </style></head><body><header><div class="brand"><b>◈</b>Sentinel</div><span class="tag">PRIVATE COMPANION</span></header><main><span class="tag">YOUR AGENTIC WORKSPACE</span><h1>A clear view. A considered decision.</h1><p class="intro">Your Robinhood account, research and decisions together. Open Sentinel in ChatGPT or Codex to refresh data and review proposals.</p>'''+('<span class="status">Workflow paused · kill switch engaged</span>' if state['kill'] else '<span class="status">Approval required for every trade</span>')+cards.join(['<div class="stats">','</div>'])+errors+'''<section class="panel"><div class="row"><h2>Account overview</h2><span class="tag">OFFICIAL ROBINHOOD OBSERVATION</span></div><p>'''+esc((snapshot.get('account')or{}).get('nickname','Agentic'))+' · '+esc((snapshot.get('account')or{}).get('account_number','Not connected'))+' · '+esc((snapshot.get('account')or{}).get('state','Unknown'))+'</p><p>Snapshot observed '+esc(snapshot.get('observedAt','Not refreshed'))+'. This page does not poll Robinhood.</p></section><section class="panel"><h2>Positions</h2>'+table(positions,['symbol','quantity','average_buy_price'])+'</section><section class="panel"><h2>Orders</h2>'+table(orders,['asset_class','symbol','side','state','quantity'])+'</section><h2>Strategy workspace</h2><div class="bots">'+bots+'</div><section class="panel"><h2>Investment committee & proposals</h2>'+proposals+'</section><section class="panel"><h2>How to use Sentinel</h2><p>Ask: <code>Refresh my Sentinel dashboard</code></p><p>Ask: <code>Run a committee review for my selected strategy</code></p><p>Ask: <code>Show Sentinel risk checks and activity</code></p><p>Ask: <code>Pause Sentinel</code></p></section><footer>'+str(state['activityCount'])+' recorded events. Risk checks are companion workflow controls, not broker-enforced restrictions. The kill switch does not cancel existing orders. Local history does not sync automatically.</footer></main></body></html>'

if __name__=='__main__':
    parser=argparse.ArgumentParser();parser.add_argument('--db',required=True);parser.add_argument('--output',required=True);args=parser.parse_args()
    state=Journal(args.db).run('status');target=Path(args.output);target.parent.mkdir(parents=True,exist_ok=True);target.write_text(render(state));target.chmod(0o600);print(str(target))
